### ISSUE TITLE
bad cache data

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/docker-builder#13]
Got these errors:
https://abf.openmandriva.org/build_lists/577762
```
bad cache data
bad cache data
Traceback (most recent call last):
  File "/mdv/build-rpm.py", line 448, in <module>
    build_rpm()
  File "/mdv/build-rpm.py", line 342, in build_rpm
    '--resultdir=' + output_dir])
  File "/usr/lib64/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/mock', '--update', '--configdir', '/etc/mock/', '--buildsrpm', '--spec=/home/omv/udisks/udisks.spec', '--source=/home/omv/udisks', '--no-cleanup-after', '--resultdir=/home/omv/output']' returned non-zero exit status 1.
```

**Comment by fedya** [comment]
BUILDSTDERR: error: Bad source: /builddir/build/SOURCES/udisks-2.8.3.tar.bz2: No such file or directory

**Comment by fedya** [comment]
It's not builder issue
You just forgot to upload the source file.
I added in logs few words about it with short explanation and error logs printing.

**Comment by tpgxyz** [comment]
I've uploaded source file, but forgot to adjust version tag :)
